### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by jnm2** [AMVSoftware/Cake.SqlServer#39]
Scripts that use Cake.SqlServer cannot be run or debugged using CoreCLR.

Can we add a `netstandard1.6` build to the package? It's okay if things like DACPAK are missing initially; i don't use them.

Willing to help/PR.

**Comment by trailmax** [comment]
There was an attempt to migrate initially, but got abandoned: https://github.com/AMVSoftware/Cake.SqlServer/pull/19

Feel free to PR if you need it sooner. I tried to get it migrated, but BACPAC/DACPAC dependencies are not yet on Core and I did not want a partial solution. But let's go there without it, as it is causing too much pain already.

**Comment by trailmax** [comment]
I've done [Cake.Hosts](https://github.com/AMVSoftware/Cake.Hosts) to work on both full-fat framework and Core - can use it as example for build script as that will have to be updated

**Comment by jnm2** [comment]
Mind if I move you to the modern csproj SDK too, like Cake.Hosts?

**Comment by trailmax** [comment]
@jnm2 go wild!

**Comment by trailmax** [comment]
@jnm2 I mean without breaking compatibility ;-P

**Comment by jnm2** [comment]
Awww...

**Comment by jnm2** [comment]
Can I get rid of the `Copy-Files` task and use MSBuild .WithTarget("Pack") to handle pulling all the files for the nupkg?

**Comment by jnm2** [comment]
This is what I have so far: https://github.com/AMVSoftware/Cake.SqlServer/compare/master...jnm2:dotnet_core_support

The last remaining part of the upgrade is to create a multi-targeting nupkg which can either be done manually (which is brittle to changing target frameworks or changing dependencies) or with MSBuild magic.

**Comment by trailmax** [comment]
@jnm2  Looks a lot cleaner - at least the projects files
Copy-Files task is a hack, so if it can be fixed go ahead. 

The remaining the the hard part - building for multi-platforms is hard.

**Comment by jnm2** [comment]
Cool.
One commit at a time. =) Makes it easier to dissect later if needed.

**Comment by jnm2** [comment]
Right now you have `<authors>Max Vasilyev</authors><owners>trailmax, cake-contrib</owners>`. Do you want to keep that or are you equally happy with `<authors>Max Vasilyev</authors><owners>Max Vasilyev</owners>` like Cake.Hosts has?

(The difference is whether to use an external .nuspec or do it all from the .csproj.)

**Comment by jnm2** [comment]
Here's the .NET Core support commit: https://github.com/AMVSoftware/Cake.SqlServer/commit/70bb7e7e452673f56699514c4b70c0fbb29e00c1

To be honest, as I expected, that was by far and away the easiest part of the whole thing. =D
Last thing that remains (besides awaiting your answer to my [last question](https://github.com/AMVSoftware/Cake.SqlServer/issues/39#issuecomment-341868893)) is testing the `netcoreapp1.0` test assembly. It'll look similar to [this](https://github.com/jnm2/ApiContractGenerator/blob/db8f28dc0fff743635c69afc10b2baddb22e509f/build.cake#L16-L26) but I need to figure out how to do the results file so it can be uploaded.

**Comment by jnm2** [comment]
Okay, there's currently no way to test NUnit on .NET Core and get test result XML. (https://github.com/nunit/nunit3-vs-adapter/issues/323). Do you want to use `NUnit3` for the `net46` dll for the TestResult.xml and `DotNetCoreTest` for the `netcoreapp1.0` dll, or `DotNetCoreTest` for both an no result XML?

**Comment by jnm2** [comment]
Decided to keep the test result XML for net46 in case it also becomes available for netcoreapp1.0.

**Comment by jnm2** [comment]
You should add an appveyor.yml to the repo to make it easy for me to set up my own AppVeyor test on my own fork.

**Comment by jnm2** [comment]
Currently blocked at https://gitter.im/cake-build/cake?at=59fe39f74ff065ac18b78e65

**Comment by trailmax** [comment]
@jnm2 re `<authors>` - keep it simple, if we can have a working solution without extra nuspec file - let's do it. 
As for the problem of loading assemblies - I have no clue

**Comment by trailmax** [comment]
use this for your appveyor.yml:
```
version: '{build}'
environment:
  NUGET_API_KEY:
    secure: 8qBLJ+Nj3wkgj/DZEtGYQK21clewDLJ5vPwf3XMgVyPn8jl5WRzzee3mc0WqEHi+
  MYGET_API_KEY:
    secure: jrnvIAlH4mF14CcASaWmRQzqXWvZw4KlSCl3u6z8NqOjW4iz5FA8SabxXPvFgdD4
  MYGET_API_URL: https://www.myget.org/F/cake-sqlserver/api/v2
nuget:
  project_feed: true
build_script:
- ps: >-
    .\build.ps1 -Target "AppVeyor" -Verbosity Diagnostic  -experimental


    .\build.ps1 -Script "tests.cake" -Verbosity Diagnostic  -experimental
test: off
```
